name: Update recent activity in README
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_NAME: NikSne
          COMMIT_EMAIL: "commits@niksne.ru"
          COMMIT_MSG: "chore (README): update recent activity"
          EMPTY_COMMIT_MSG: "chore (README): empty commit to keep \"Recent Activity\" workflow active after 60 days of no activity"
